services:
  gradio-app:
    extends:
      file: compose.base.yml
      service: gradio-app
    image: ghcr.io/sergey21000/yolo-detector:main-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]