services:
  gradio-app:
    container_name: yolo_detector
    restart: on-failure
    ports:
      - 7860:7860
    volumes:
      - ../models:/app/models
      - ../runs:/app/runs
      - ../config.py:/app/config.py
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860